import { Geist, Geist_Mono } from "next/font/google";
import { Button } from "@heroui/react";
import { EllipsisVertical, Pencil } from "@gravity-ui/icons";

import { LayoutX } from "@/components/layout-x";
import { cn } from "@/lib/utils";
import { appRouter } from "@/config/routes";
import { workspaceRoute } from "@/config/workspace-route";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sidebarHeaderBtnClass =
  "size-7 min-w-7 shrink-0 rounded-md! p-0 text-fg-3 hover:bg-canvas-2! hover:text-fg-1!";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className="min-h-full flex flex-col">
        <LayoutX route={workspaceRoute}>
          <LayoutX.Rail>
            <LayoutX.RailHeader>
              <div className="flex items-center justify-center py-3">
                <div
                  className="flex h-8 w-8 items-center justify-center rounded-[9px] bg-canvas-2 text-[11px] font-semibold tracking-[-0.01em] text-fg-1"
                  title="Brand / Logo"
                >
                  LX
                </div>
              </div>
            </LayoutX.RailHeader>
            <LayoutX.RailMain>
              <LayoutX.RailRouteNav />
            </LayoutX.RailMain>
            <LayoutX.RailFooter>
              <div className="flex justify-center py-3">
                <div
                  className="h-7 w-7 rounded-full bg-linear-to-br from-[#EFC6A7] to-[#E8763A]"
                  title="Account"
                />
              </div>
            </LayoutX.RailFooter>
          </LayoutX.Rail>
          <LayoutX.Sidebar>
            <LayoutX.SidebarHeader>
              <div className="sb-head flex items-center px-2 py-3">
                <div className="flex-1 min-w-0">
                  <div className="sb-title font-medium text-[1rem] text-fg-1 truncate">
                    Workspace
                  </div>
                  <div className="sb-title-sub text-xs text-fg-4 truncate">
                    Workspace · Astrid
                  </div>
                </div>
                <Button
                  isIconOnly
                  size="sm"
                  variant="ghost"
                  aria-label="Edit"
                  className={sidebarHeaderBtnClass}
                >
                  <Pencil className="size-3.5 text-current" />
                </Button>
                <Button
                  isIconOnly
                  size="sm"
                  variant="ghost"
                  aria-label="More"
                  className={cn(sidebarHeaderBtnClass, "ml-1")}
                >
                  <EllipsisVertical className="size-3.5 text-current" />
                </Button>
              </div>
            </LayoutX.SidebarHeader>
            <LayoutX.SidebarMain />
            <LayoutX.SidebarFooter>
              <div className="flex items-center gap-2 px-2.5 py-3 text-[12.5px] text-fg-3">
                <div className="flex size-7 items-center justify-center rounded-full bg-linear-to-br from-[#EFC6A7] to-[#E8763A] text-[11px] font-semibold text-white">
                  LX
                </div>
                <div className="flex min-w-0 flex-col leading-tight">
                  <span className="truncate text-fg-1 font-medium">
                    layout-x
                  </span>
                  <span className="truncate text-[10.5px] text-fg-4 font-mono uppercase tracking-[0.12em]">
                    Workspace
                  </span>
                </div>
              </div>
            </LayoutX.SidebarFooter>
          </LayoutX.Sidebar>
          <LayoutX.Content>
            <LayoutX.ContentHeader breadcrumbRoute={appRouter} />
            <LayoutX.ContentBody>{children}</LayoutX.ContentBody>
          </LayoutX.Content>
        </LayoutX>
      </body>
    </html>
  );
}
