import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { LayoutX } from "@/components/layout-x";
import { workspaceSidebarContent } from "@/config/workspace-sidebar-content";
import { appRouter } from "@/config/routes";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="zh-CN"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <LayoutX>
          <LayoutX.Rail>
            <LayoutX.RailHeader>
              <div className="flex items-center justify-center p-2">
                <div
                  className="flex h-8 w-8 items-center justify-center rounded-md bg-foreground/10 text-xs font-semibold text-foreground"
                  title="品牌 / Logo"
                >
                  LX
                </div>
              </div>
            </LayoutX.RailHeader>
            <LayoutX.RailMain>
              <nav
                className="flex flex-col items-center gap-1 p-1"
                aria-label="快捷入口"
              >
                {["搜", "邮", "日", "档"].map((t) => (
                  <div
                    key={t}
                    className="flex h-9 w-9 cursor-default items-center justify-center rounded-md text-xs text-foreground/80 hover:bg-foreground/10"
                    title={t}
                  >
                    {t}
                  </div>
                ))}
              </nav>
            </LayoutX.RailMain>
            <LayoutX.RailFooter>
              <div className="flex justify-center p-2">
                <div
                  className="h-7 w-7 rounded-full bg-foreground/15"
                  title="账户"
                />
              </div>
            </LayoutX.RailFooter>
          </LayoutX.Rail>
          <LayoutX.Sidebar>
            <LayoutX.SidebarHeader>
              <div className="px-3 py-2.5 text-sm font-medium text-foreground dark:border-white/10">
                导航
              </div>
            </LayoutX.SidebarHeader>
            <LayoutX.SidebarMain content={workspaceSidebarContent} />
            <LayoutX.SidebarFooter>
              <div className="px-3 py-2 text-xs text-foreground/55 dark:border-white/10">
                layout-x · 侧栏底栏占位
              </div>
            </LayoutX.SidebarFooter>
          </LayoutX.Sidebar>
          <LayoutX.Content>
            <LayoutX.ContentHeader breadcrumbRoute={appRouter} />
            <LayoutX.ContentBody>{children}</LayoutX.ContentBody>
          </LayoutX.Content>
        </LayoutX>
      </body>
    </html>
  );
}
